module "alert-api" {
  source = "alert-api"
  image = "expediadotcom/haystack-alert-api:${var.haystack-alerts["version"]}"
  replicas = "${var.haystack-alerts["alert-api_instances"]}"
  enabled = "${var.haystack-alerts["enabled"]}"
  cpu_limit = "${var.haystack-alerts["alert-api_cpu_limit"]}"
  cpu_request = "${var.haystack-alerts["alert-api_cpu_request"]}"
  memory_limit = "${var.haystack-alerts["alert-api_memory_limit"]}"
  memory_request = "${var.haystack-alerts["alert-api_memory_request"]}"
  jvm_memory_limit = "${var.haystack-alerts["alert-api_jvm_memory_limit"]}"
  env_vars = "${var.haystack-alerts["alert-api_environment_overrides"]}"
  namespace = "${var.namespace}"
  subscription_service_endpoint = "${var.haystack-alerts["subscription_service_hostname"]}:${var.haystack-alerts["subscription_service_port"]}"
  elasticsearch_template = "${var.haystack-alerts["elasticsearch_template"]}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  graphite_enabled = "${var.graphite_enabled}"
  node_selector_label = "${var.node_selector_label}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  elasticsearch_endpoint = "${var.elasticsearch_hostname}:${var.elasticsearch_port}"
}

module "anomaly-store" {
  source = "anomaly-store"
  image = "expediadotcom/haystack-anomaly-store:${var.haystack-alerts["version"]}"
  replicas = "${var.haystack-alerts["anomaly-store_instances"]}"
  enabled = "${var.haystack-alerts["enabled"]}"
  cpu_limit = "${var.haystack-alerts["anomaly-store_cpu_limit"]}"
  cpu_request = "${var.haystack-alerts["anomaly-store_cpu_request"]}"
  memory_limit = "${var.haystack-alerts["anomaly-store_memory_limit"]}"
  memory_request = "${var.haystack-alerts["anomaly-store_memory_request"]}"
  jvm_memory_limit = "${var.haystack-alerts["anomaly-store_jvm_memory_limit"]}"
  env_vars = "${var.haystack-alerts["anomaly-store_environment_overrides"]}"
  elasticsearch_template = "${var.haystack-alerts["elasticsearch_template"]}"
  namespace = "${var.namespace}"
  kafka_endpoint = "${var.kafka_hostname}:${var.kafka_port}"
  elasticsearch_endpoint = "${var.elasticsearch_hostname}:${var.elasticsearch_port}"
  graphite_hostname = "${var.graphite_hostname}"
  graphite_port = "${var.graphite_port}"
  graphite_enabled = "${var.graphite_enabled}"
  node_selector_label = "${var.node_selector_label}"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
}

module "es-indices-curator" {
  source = "es-indices-curator"
  kubectl_executable_name = "${var.kubectl_executable_name}"
  kubectl_context_name = "${var.kubectl_context_name}"
  enabled = "${var.haystack-alerts["es_curator_enabled"]}"
  elasticsearch_hostname = "${var.elasticsearch_hostname}"
  elasticsearch_port = "${var.elasticsearch_port}"
  namespace = "${var.namespace}"
}